---
Jobs:
    - Name: job_id1
      Vertices: [job_id4]
      Job: GCD

    - Name: job_id2
      Vertices: [job_id4]
      Job: FibNumberRemainderCount

    - Name: job_id3
      Vertices: [job_id5]
      Job: HanoiTower

    - Name: job_id4
      Vertices: [job_id6]
      Job: Sum

    - Name: job_id5
      Vertices: [job_id6]
      Job: DumbFib

    - Name: job_id6
      Vertices: []
      Job: Void
...
