---
Jobs:
    - Name: job_id1
      Vertices: [job_id4, job_id5]
      Job: GCD(1164182481, 717245)

    - Name: job_id2
      Vertices: [job_id4]
      Job: FibNumberRemainderCount(100)

    - Name: job_id3
      Vertices: [job_id5, job_id6]
      Job: HanoiTower(10, 1, 3, 2)

    - Name: job_id4
      Vertices: [job_id6]
      Job: Sum(324515, 531348)

    - Name: job_id5
      Vertices: [job_id6]
      Job: DumbFib(19)

    - Name: job_id6
      Vertices: []
      Job: Void()
...
